import type { MockProduct, LayoutTemplate, TemplateSize, LayoutElement } from "../types/layout";

export const MOCK_PRODUCTS: MockProduct[] = [
  {
    id: "prod-001",
    name: "Goiaba Vermelha KG",
    rawData: "Preço regular: 7!@# .19!@#1KG R$7.19!@#Tributos Aprox.: R$.3(4.2%)",
  },
  {
    id: "prod-002",
    name: "Mamão Formosa KG",
    rawData: "Preço regular: 12!@# .99!@#1KG R$43.3!@#R$2.88(22.2%)",
  },
  {
    id: "prod-003",
    name: "Banana Prata KG",
    rawData: "Preço de por: 24!@# .49!@#16!@# .19!@#1KG R$46.26!@#R$3.83(23.63%)",
  },
  {
    id: "prod-004",
    name: "Uva Thompson Sem Semente KG",
    rawData: "Preço de por: 18!@# .90!@#14!@# .99!@#1KG R$38.50!@#R$3.15(21.1%)",
  },
];

const BASE_FONT = "Arial, sans-serif";

const gondolaElements: LayoutElement[] = [
  {
    id: "el-produto",
    label: "Nome do Produto",
    text: "{{nome}}",
    x: 0.8,
    y: 0.35,
    fontSize: 6,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-simbolo",
    label: "Símbolo R$",
    text: "R$",
    x: 0.3,
    y: 1.15,
    fontSize: 13,
    fontWeight: "900",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-preco",
    label: "Preço Principal",
    text: "{{reais}}.{{centavos}}",
    x: 2.2,
    y: 0.9,
    fontSize: 22,
    fontWeight: "900",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-preco-de-label",
    label: "Label Preço De",
    text: "PREÇO DE",
    x: 2.8,
    y: 1.85,
    fontSize: 3.5,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-referencia",
    label: "Unidade / Referência",
    text: "{{referencia}}",
    x: 2.8,
    y: 2.05,
    fontSize: 3.5,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-codigo",
    label: "Código PLU",
    text: "*1443*",
    x: 0.3,
    y: 2.1,
    fontSize: 3.5,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-tributos",
    label: "Tributos",
    text: "{{tributos}}",
    x: 0.3,
    y: 2.35,
    fontSize: 3.5,
    fontWeight: "normal",
    color: "#333333",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
];

const promocaoElements: LayoutElement[] = [
  {
    id: "el-produto",
    label: "Nome do Produto",
    text: "{{nome}}",
    x: 1.5,
    y: 0.5,
    fontSize: 11,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-simbolo",
    label: "Símbolo R$",
    text: "R$",
    x: 0.6,
    y: 1.9,
    fontSize: 22,
    fontWeight: "900",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-preco",
    label: "Preço Principal",
    text: "{{reais}}.{{centavos}}",
    x: 4.4,
    y: 1.4,
    fontSize: 38,
    fontWeight: "900",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-preco-de-label",
    label: "Label Preço De",
    text: "PREÇO DE",
    x: 5.5,
    y: 3.1,
    fontSize: 6,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-referencia",
    label: "Unidade / Referência",
    text: "{{referencia}}",
    x: 5.5,
    y: 3.45,
    fontSize: 6,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-codigo",
    label: "Código PLU",
    text: "*1443*",
    x: 0.6,
    y: 3.5,
    fontSize: 6,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-tributos",
    label: "Tributos",
    text: "{{tributos}}",
    x: 0.6,
    y: 3.95,
    fontSize: 5.5,
    fontWeight: "normal",
    color: "#333333",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
];

const simplesElements: LayoutElement[] = [
  {
    id: "el-produto",
    label: "Nome do Produto",
    text: "{{nome}}",
    x: 0.25,
    y: 0.2,
    fontSize: 7,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-simbolo",
    label: "Símbolo R$",
    text: "R$",
    x: 0.25,
    y: 1.1,
    fontSize: 9,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-preco",
    label: "Preço Principal",
    text: "{{precoCompleto}}",
    x: 1.3,
    y: 0.85,
    fontSize: 24,
    fontWeight: "900",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-tributos",
    label: "Tributos",
    text: "{{tributos}}",
    x: 0.25,
    y: 3.65,
    fontSize: 3.5,
    fontWeight: "normal",
    color: "#888888",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
];

export const MOCK_TEMPLATES: LayoutTemplate[] = [
  {
    id: "tpl-gondola-5x3",
    name: "Etiqueta Gôndola",
    width: "5cm",
    height: "3cm",
    elements: gondolaElements,
  },
  {
    id: "tpl-promocao-10x5",
    name: "Cartaz Promoção",
    width: "10cm",
    height: "5cm",
    elements: promocaoElements,
  },
  {
    id: "tpl-simples-8x4",
    name: "Etiqueta Simples",
    width: "8cm",
    height: "4cm",
    elements: simplesElements,
  },
];

export const TEMPLATE_SIZES: TemplateSize[] = [
  {
    label: "Etiqueta Gôndola",
    description: "5 × 3 cm — Padrão para gondola de supermercado",
    width: "5cm",
    height: "3cm",
    starterElements: gondolaElements,
  },
  {
    label: "Cartaz Promoção",
    description: "10 × 5 cm — Destaque para promoções",
    width: "10cm",
    height: "5cm",
    starterElements: promocaoElements,
  },
  {
    label: "Etiqueta Simples",
    description: "8 × 4 cm — Versátil para diversos produtos",
    width: "8cm",
    height: "4cm",
    starterElements: simplesElements,
  },
];
