import type { MockProduct, LayoutTemplate, TemplateSize, LayoutElement } from "../types/layout";

export const MOCK_PRODUCTS: MockProduct[] = [
  {
    id: "prod-1443",
    code: "1443",
    name: "GOIABA VERMELHA KG",
    barcode: "7891234014431",
    rawData: "Preço regular: 7!@# .19!@#1KG R$7.19!@#Tributos Aprox.: R$.3(4.2%)",
  },
  {
    id: "prod-35",
    code: "35",
    name: "MOELA FRANGO REGINA RESF.500G BDJ - UN UN",
    barcode: "7891234000359",
    rawData: "Preço regular: 8!@# .90!@#1UN R$8.90!@#Tributos Aprox.: R$.4(5.1%)",
  },
  {
    id: "prod-124",
    code: "124",
    name: "ENTREGA BAIRRO - UN UN",
    barcode: "7891234001240",
    rawData: "Preço regular: 5!@# .00!@#1UN R$5.00!@#Tributos Aprox.: R$.2(4.0%)",
  },
  {
    id: "prod-1201",
    code: "1201",
    name: "PIZZA MARGUERITA PEQUENA UND - UN UN",
    barcode: "7891234012017",
    rawData: "Preço regular: 14!@# .58!@#1UN R$14.58!@#Tributos Aprox.: R$.31(4.2%)",
  },
  {
    id: "prod-1228",
    code: "1228",
    name: "PIZZA MARINARA PEQUENA UND - UN UN",
    barcode: "7891234012284",
    rawData: "Preço de por: 18!@# .90!@#14!@# .90!@#1UN R$14.90!@#Tributos Aprox.: R$.35(4.5%)",
  },
  {
    id: "prod-1252",
    code: "1252",
    name: "PIZZA DOM BOSCO GRANDE UND - KG KG",
    barcode: "7891234012529",
    rawData: "Preço regular: 28!@# .90!@#1KG R$28.90!@#Tributos Aprox.: R$.95(5.2%)",
  },
  {
    id: "prod-1260",
    code: "1260",
    name: "PIZZA BACON C/CATUPIRY PEQUENA UND - UN UN",
    barcode: "7891234012604",
    rawData: "Preço de por: 22!@# .90!@#17!@# .90!@#1UN R$17.90!@#Tributos Aprox.: R$.45(4.8%)",
  },
  {
    id: "prod-1287",
    code: "1287",
    name: "PIZZA BANANA PEQUENA UND - UN UN",
    barcode: "7891234012871",
    rawData: "Preço regular: 15!@# .90!@#1UN R$15.90!@#Tributos Aprox.: R$.38(4.3%)",
  },
  {
    id: "prod-002",
    code: "433",
    name: "Mamão Formosa KG",
    barcode: "7891234004333",
    rawData: "Preço regular: 12!@# .99!@#1KG R$43.3!@#R$2.88(22.2%)",
  },
  {
    id: "prod-003",
    code: "462",
    name: "Banana Prata KG",
    barcode: "7891234004623",
    rawData: "Preço de por: 24!@# .49!@#16!@# .19!@#1KG R$46.26!@#R$3.83(23.63%)",
  },
];

const BASE_FONT = "Arial, sans-serif";

const gondolaElements: LayoutElement[] = [
  {
    id: "el-produto",
    label: "Nome do Produto",
    text: "{{nome}}",
    x: 0.8,
    y: 0.35,
    fontSize: 6,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-simbolo",
    label: "Símbolo R$",
    text: "R$",
    x: 0.3,
    y: 1.15,
    fontSize: 13,
    fontWeight: "900",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-preco",
    label: "Preço Principal",
    text: "{{reais}}.{{centavos}}",
    x: 2.2,
    y: 0.9,
    fontSize: 22,
    fontWeight: "900",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-preco-de-label",
    label: "Label Preço De",
    text: "PREÇO DE",
    x: 2.8,
    y: 1.85,
    fontSize: 3.5,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-referencia",
    label: "Unidade / Referência",
    text: "{{referencia}}",
    x: 2.8,
    y: 2.05,
    fontSize: 3.5,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-codigo",
    label: "Código PLU",
    text: "*1443*",
    x: 0.3,
    y: 2.1,
    fontSize: 3.5,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-tributos",
    label: "Tributos",
    text: "{{tributos}}",
    x: 0.3,
    y: 2.35,
    fontSize: 3.5,
    fontWeight: "normal",
    color: "#333333",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
];

const promocaoElements: LayoutElement[] = [
  {
    id: "el-produto",
    label: "Nome do Produto",
    text: "{{nome}}",
    x: 1.5,
    y: 0.5,
    fontSize: 11,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-simbolo",
    label: "Símbolo R$",
    text: "R$",
    x: 0.6,
    y: 1.9,
    fontSize: 22,
    fontWeight: "900",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-preco",
    label: "Preço Principal",
    text: "{{reais}}.{{centavos}}",
    x: 4.4,
    y: 1.4,
    fontSize: 38,
    fontWeight: "900",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-preco-de-label",
    label: "Label Preço De",
    text: "PREÇO DE",
    x: 5.5,
    y: 3.1,
    fontSize: 6,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-referencia",
    label: "Unidade / Referência",
    text: "{{referencia}}",
    x: 5.5,
    y: 3.45,
    fontSize: 6,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-codigo",
    label: "Código PLU",
    text: "*1443*",
    x: 0.6,
    y: 3.5,
    fontSize: 6,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-tributos",
    label: "Tributos",
    text: "{{tributos}}",
    x: 0.6,
    y: 3.95,
    fontSize: 5.5,
    fontWeight: "normal",
    color: "#333333",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
];

const simplesElements: LayoutElement[] = [
  {
    id: "el-produto",
    label: "Nome do Produto",
    text: "{{nome}}",
    x: 0.25,
    y: 0.2,
    fontSize: 7,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-simbolo",
    label: "Símbolo R$",
    text: "R$",
    x: 0.25,
    y: 1.1,
    fontSize: 9,
    fontWeight: "bold",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-preco",
    label: "Preço Principal",
    text: "{{precoCompleto}}",
    x: 1.3,
    y: 0.85,
    fontSize: 24,
    fontWeight: "900",
    color: "#111111",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
  {
    id: "el-tributos",
    label: "Tributos",
    text: "{{tributos}}",
    x: 0.25,
    y: 3.65,
    fontSize: 3.5,
    fontWeight: "normal",
    color: "#888888",
    textAlign: "left",
    fontFamily: BASE_FONT,
  },
];

export const MOCK_TEMPLATES: LayoutTemplate[] = [
  {
    id: "tpl-gondola-5x3",
    name: "Etiqueta Gôndola",
    width: "5cm",
    height: "3cm",
    elements: gondolaElements,
  },
  {
    id: "tpl-promocao-10x5",
    name: "Cartaz Promoção",
    width: "10cm",
    height: "5cm",
    elements: promocaoElements,
  },
  {
    id: "tpl-simples-8x4",
    name: "Etiqueta Simples",
    width: "8cm",
    height: "4cm",
    elements: simplesElements,
  },
];

export const TEMPLATE_SIZES: TemplateSize[] = [
  {
    label: "Etiqueta Gôndola",
    description: "5 × 3 cm — Padrão para gondola de supermercado",
    width: "5cm",
    height: "3cm",
    starterElements: gondolaElements,
  },
  {
    label: "Cartaz Promoção",
    description: "10 × 5 cm — Destaque para promoções",
    width: "10cm",
    height: "5cm",
    starterElements: promocaoElements,
  },
  {
    label: "Etiqueta Simples",
    description: "8 × 4 cm — Versátil para diversos produtos",
    width: "8cm",
    height: "4cm",
    starterElements: simplesElements,
  },
];
